### ISSUE TITLE
is SPI.begin() missing?

### ISSUE THREAD

**Issue by x29a** [nwb99/MCP4151#1]
Hi there,

thanks for the lib!

Was there a reason not to use ` SPI.begin()` (https://www.arduino.cc/reference/en/language/functions/communication/spi/begin/) in the constructors instead of:

https://github.com/nwb99/MCP4151/blob/63f302bb898d84d319918811c4abe9015e732ce9/src/MCP4151.cpp#L25-L30

https://github.com/nwb99/MCP4151/blob/63f302bb898d84d319918811c4abe9015e732ce9/src/MCP4151.cpp#L42-L46

BR

**Comment by nwb99** [comment]
Honestly I cannot remember. This was my first library I wrote myself, so it's possible I had some weird issue and worked around it by doing it like this. Please feel free to modify it on your end, test, and post your results! Hope it's useful to you. :)
